"""Ferry's wordmark — the mark and block letterforms shown when the tool starts.

Compact block letters beside a hull-and-wake mark, chosen 2026-08-22 after the
first two attempts (a plain wake, then two shores with a crossing) read as too
static::

        ╷    ┏━╸ ┏━╸ ┏━┓ ┏━┓ ╻ ╻
      ╰───╯  ┣╸  ┣╸  ┣┳┛ ┣┳┛ ┗┳┛
     ≈  ≈  ≈ ╹   ┗━╸ ╹┗╸ ╹┗╸  ╹

The hull holds still and the wake beneath it drifts leftward, so the ferry
reads as sailing to the right — the same direction the letters reveal. The
wake is generated by :func:`~ferry.cli.motion.wake_row` rather than stored as
frames, which is what lets the same mark run as an endless spinner during long
work instead of being a one-shot title animation.

Everything has an ASCII twin, because a console reporting ``cp1252`` cannot
encode any of these glyphs and would raise rather than look wrong.
"""

from __future__ import annotations

import time
from dataclasses import dataclass

from ferry import __version__
from ferry.cli.motion import wake_row
from ferry.cli.theme import ASCII_ICONS, Theme

__all__ = ["MARK_WIDTH", "TAGLINE", "Wordmark", "build_wordmark", "render"]

TAGLINE = "carry your conversations across"

MARK_WIDTH = 7
"""Columns the mark occupies. Every mark row is padded to exactly this."""

_HULL_ROWS = ("   ╷   ", " ╰───╯ ")
"""Funnel and hull. The third row is the wake, which is generated per frame."""

_ASCII_HULL_ROWS = ("   |   ", r" \___/ ")

_LETTERS: dict[str, tuple[str, str, str]] = {
    "F": ("┏━╸", "┣╸ ", "╹  "),
    "E": ("┏━╸", "┣╸ ", "┗━╸"),
    "R": ("┏━┓", "┣┳┛", "╹┗╸"),
    "Y": ("╻ ╻", "┗┳┛", " ╹ "),
}

_ASCII_NAME = "F E R R Y"

_REVEAL_COLUMNS_PER_FRAME = 3
"""How much of the letterform block appears each frame during the reveal."""

_SAIL_FRAMES = 9
"""Frames the wake keeps drifting after the letters have finished appearing.

Without these the animation stops the instant the name completes, which reads
as a stutter rather than an ending.
"""

_BANNER_FRAME_SECONDS = 0.055
"""Banner frame interval.

Faster than :data:`~ferry.cli.motion.FRAME_SECONDS` because this is a one-shot
that must not delay startup: the whole thing runs in well under a second. The
wake advances every second frame so it still drifts at a readable speed.
"""


@dataclass(frozen=True)
class Wordmark:
    """The wordmark resolved for one theme.

    Held as rows rather than a finished string so the reveal can draw a partial
    number of columns, and so the wake row can be regenerated per frame,
    without rebuilding anything.
    """

    hull_rows: tuple[str, ...]
    letter_rows: tuple[str, ...]
    version: str
    tagline: str
    ascii_only: bool

    @property
    def width(self) -> int:
        """Width of the letterform block, in columns.

        The widest row, not the first — in the ASCII form the name sits on the
        middle row and the outer two are empty, so measuring row zero gave a
        width of nought and blanked the whole wordmark.
        """
        return max(len(row) for row in self.letter_rows)

    def mark_rows(self, phase: int = 0) -> tuple[str, ...]:
        """The three mark rows with the wake drawn at ``phase``.

        Args:
            phase: Animation tick. Any integer; the wake cycles.
        """
        mark, gap = ("~", " ") if self.ascii_only else ("≈", " ")
        wake = wake_row(MARK_WIDTH, phase, mark=mark, gap=gap)
        return (*self.hull_rows, wake)

    def reveal(self, columns: int) -> tuple[str, ...]:
        """The letterform rows truncated to ``columns`` characters.

        Args:
            columns: How much of the block has been drawn. Clamped to the
                block's own width.
        """
        cut = max(0, min(columns, self.width))
        return tuple(row[:cut] for row in self.letter_rows)


def build_wordmark(theme: Theme, *, version: str = __version__) -> Wordmark:
    """Assemble the wordmark using glyphs the theme can actually render."""
    ascii_only = theme.icons is ASCII_ICONS
    if ascii_only:
        return Wordmark(
            hull_rows=_ASCII_HULL_ROWS,
            letter_rows=("", _ASCII_NAME, ""),
            version=version,
            tagline=TAGLINE,
            ascii_only=True,
        )
    rows = tuple(" ".join(_LETTERS[letter][row] for letter in "FERRY") for row in range(3))
    return Wordmark(
        hull_rows=_HULL_ROWS,
        letter_rows=rows,
        version=version,
        tagline=TAGLINE,
        ascii_only=False,
    )


def render(ui: object, theme: Theme, *, animate: bool = True) -> None:
    """Print the wordmark: letters revealing left to right, wake sailing.

    Args:
        ui: The :class:`~ferry.cli.ui.UI` doing the printing.
        theme: Active theme.
        animate: Whether to animate. Suppressed anyway when the theme carries
            no colour or output is not a terminal, so nothing writes
            cursor-control sequences into a log.
    """
    from rich.live import Live
    from rich.text import Text

    from ferry.cli.ui import UI

    assert isinstance(ui, UI)
    wm = build_wordmark(theme)
    console = ui.console
    coloured = theme.uses_color

    def frame(columns: int, phase: int) -> Text:
        out = Text()
        letters = wm.reveal(columns)
        for index, mark_row in enumerate(wm.mark_rows(phase)):
            out.append("  ")
            out.append(mark_row, style="ferry.accent" if coloured else "")
            out.append("  ")
            out.append(letters[index], style="ferry.heading" if coloured else "")
            if index == 0 and columns >= wm.width:
                out.append(f"   {wm.version}", style="ferry.dim" if coloured else "")
            out.append("\n")
        out.append("  ")
        out.append(wm.tagline, style="ferry.dim" if coloured else "")
        out.append("\n")
        return out

    console.print()
    if not (animate and coloured and ui.interactive):
        console.print(frame(wm.width, 0))
        return

    reveal_frames = -(-wm.width // _REVEAL_COLUMNS_PER_FRAME)
    with Live(frame(0, 0), console=console, refresh_per_second=60, transient=False) as live:
        for tick in range(reveal_frames + _SAIL_FRAMES + 1):
            live.update(frame(tick * _REVEAL_COLUMNS_PER_FRAME, tick // 2))
            time.sleep(_BANNER_FRAME_SECONDS)
