"""Animation state for Ferry's interface — pure data, no terminal involved.

Everything that moves on screen is defined here as a function of an integer
tick, so the renderers stay dumb and the behaviour stays testable. A frame is
just a string; picking one is ``frames[tick % len(frames)]``.

Two things animate:

- the **wake** under the ferry mark, a drifting pattern generated by
  :func:`wake_row` rather than hand-written frames, so it can be any width
- the **menu icons**, one :class:`Motion` per action, animated only while the
  row is under the cursor

Every glyph used here is on :data:`~ferry.cli.theme.TEXT_ONLY_GLYPHS` and was
checked against the Unicode ``emoji-data.txt`` Emoji property — see
``tests/test_motion.py``, which re-checks the whole set offline.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

__all__ = [
    "FRAME_SECONDS",
    "MENU_FRAME_SECONDS",
    "ICON_CELL",
    "MENU_MOTION",
    "Motion",
    "WAKE_PERIOD",
    "moored_frame",
    "spinner_frames",
    "wake_row",
]

FRAME_SECONDS: Final = 0.12
"""Seconds per tick for the spinner and progress column — about 8fps.

Deliberately slow. A repaint loop inside a full-screen prompt_toolkit
application costs a full redraw each tick, and over SSH or a slow terminal a
fast one strobes. Eight frames a second reads as motion without flickering.
"""

MENU_FRAME_SECONDS: Final = 0.3
"""Seconds per tick for the menu icons — 5fps, slower than the spinner.

The two rates are deliberately different. A spinner is saying "work is
happening" and wants to look busy; a menu icon sits under the cursor for as
long as someone is reading the six labels beside it, and at spinner speed it
fidgets. Slower reads as deliberate.
"""

WAKE_PERIOD: Final = 3
"""Columns between one wake mark and the next."""


def wake_row(width: int, phase: int, *, mark: str = "≈", gap: str = " ") -> str:
    """One row of drifting wake.

    The marks sit every :data:`WAKE_PERIOD` columns and shift one column left
    per phase, so the water appears to flow past a stationary hull — which is
    what makes the ferry read as sailing to the right, the same direction the
    wordmark reveals.

    Args:
        width: How many columns to fill.
        phase: The animation tick. Any integer, including negative.
        mark: Glyph for a wake crest.
        gap: Glyph for the space between crests.

    Returns:
        A string exactly ``width`` characters long.
    """
    if width <= 0:
        return ""
    return "".join(mark if (col + phase) % WAKE_PERIOD == 0 else gap for col in range(width))


def spinner_frames(width: int = 6, *, ascii_only: bool = False) -> tuple[str, ...]:
    """The ferry spinner: a hull with wake trailing behind it.

    Used for indeterminate waits instead of a generic dot spinner, so the same
    mark that opens the program is the one that shows it working.

    Args:
        width: Columns of wake behind the hull.
        ascii_only: Use ASCII glyphs, for consoles that cannot encode the others.

    Returns:
        One frame per phase of the wake cycle.
    """
    mark, gap, hull = ("~", " ", ">") if ascii_only else ("≈", " ", "▸")
    return tuple(wake_row(width, phase, mark=mark, gap=gap) + hull for phase in range(WAKE_PERIOD))


def moored_frame(width: int = 3, *, ascii_only: bool = False) -> str:
    """The hull at rest with the wake settled, for when work has finished.

    Lives here rather than beside its caller so every glyph Ferry can draw
    stays inside the handful of modules the non-ASCII guard exempts.

    Args:
        width: Columns of (now empty) water behind the hull. Match whatever
            was passed to :func:`spinner_frames` so nothing shifts on arrival.
        ascii_only: Use ASCII glyphs.
    """
    return " " * width + (">" if ascii_only else "▸")


@dataclass(frozen=True)
class Motion:
    """An animated icon for one menu action.

    Args:
        frames: The animation, played while the row is selected.
        ascii_frames: The same animation in ASCII.
        rest: The still frame shown when the row is *not* selected. Separate
            from ``frames[0]`` on purpose — a resting icon should look calm,
            not like an animation paused at an arbitrary point.
        ascii_rest: ``rest`` in ASCII.
        styles: Theme colour tokens cycled alongside the frames. Usually one.
            The theme picker's own icon uses several, so its colour rotates
            while its glyph stays put.
    """

    frames: tuple[str, ...]
    ascii_frames: tuple[str, ...]
    rest: str
    ascii_rest: str
    styles: tuple[str, ...] = ("primary",)

    def __post_init__(self) -> None:
        if not self.frames or not self.ascii_frames or not self.styles:
            raise ValueError("a motion needs at least one frame and one style")
        if len({len(f) for f in self.frames} | {len(self.rest)}) != 1:
            raise ValueError(f"ragged frames would shift the label: {self.frames}")
        if len({len(f) for f in self.ascii_frames} | {len(self.ascii_rest)}) != 1:
            raise ValueError(f"ragged ascii frames: {self.ascii_frames}")
        if not "".join(self.ascii_frames + (self.ascii_rest,)).isascii():
            raise ValueError("ascii frames must actually be ascii")

    def frame(self, tick: int, *, selected: bool = True, ascii_only: bool = False) -> str:
        """The glyph to draw this tick."""
        if not selected:
            return self.ascii_rest if ascii_only else self.rest
        frames = self.ascii_frames if ascii_only else self.frames
        return frames[tick % len(frames)]

    def style(self, tick: int, *, selected: bool = True) -> str:
        """The theme colour token to draw it in."""
        if not selected:
            return "dim"
        return self.styles[tick % len(self.styles)]

    def width(self, *, ascii_only: bool = False) -> int:
        """Column width of this icon, constant across its frames."""
        return len(self.ascii_rest if ascii_only else self.rest)


ICON_CELL: Final = 5
"""Columns every menu icon occupies.

Five gives the crossing room to read as a crossing: the hull needs somewhere
to set off from and somewhere to arrive, and the wake needs two crests behind
it before the pattern is legible as water rather than as noise.

Every icon is padded to exactly this, and every *resting* icon puts its mark in
the middle column, so a menu nobody is touching has one straight column of
markers. Only the row under the cursor travels.
"""


def _crossing(*, inbound: bool, ascii_only: bool) -> tuple[str, ...]:
    """A hull crossing the cell, wake trailing behind it.

    The hull genuinely travels — it enters one side, crosses, and leaves the
    other — because a ferry that holds station is not making a crossing.

    The wake is a **decaying trail**, not the periodic pattern
    :func:`wake_row` draws under the wordmark, and the difference is physical
    rather than decorative: the wordmark's hull is stationary with water
    flowing past it, so its crests repeat forever, while this hull is moving
    and leaves disturbance that settles. Spacing the trail by
    :data:`WAKE_PERIOD` made the second crest appear from nowhere on the last
    frame, at a distance that had no relationship to the frames before it. A
    fresh crest directly astern and a fading one behind that holds the same
    shape on every frame of the crossing.

    Alignment is preserved by the *resting* frame rather than by pinning the
    hull: only the selected row animates, so every other marker is sitting in
    the middle column while this one sails.

    Args:
        inbound: Mirror it — hull facing left, arriving from the right.
        ascii_only: Use ASCII glyphs.
    """
    fresh, faded, gap = ("~", ".", " ") if ascii_only else ("≈", "·", " ")
    hull = ("<" if ascii_only else "◂") if inbound else (">" if ascii_only else "▸")

    frames = []
    for position in range(ICON_CELL):
        cells = []
        for column in range(position):
            astern = position - column
            cells.append(fresh if astern == 1 else faded if astern == 2 else gap)
        row = "".join(cells) + hull + gap * (ICON_CELL - position - 1)
        frames.append(row[::-1] if inbound else row)
    return tuple(frames)


def _still(glyph: str) -> str:
    """One glyph centred in the icon cell, no wake."""
    return glyph.center(ICON_CELL)


MENU_MOTION: Final[dict[str, Motion]] = {
    # Export and import are mirror images of the mark itself: the same hull,
    # the same wake, the same generator. The two core operations should be
    # distinguishable before the labels are read, and both should read as the
    # thing on the banner.
    "export": Motion(
        frames=_crossing(inbound=False, ascii_only=False),
        ascii_frames=_crossing(inbound=False, ascii_only=True),
        rest=_still("▸"),
        ascii_rest=_still(">"),
    ),
    "import": Motion(
        frames=_crossing(inbound=True, ascii_only=False),
        ascii_frames=_crossing(inbound=True, ascii_only=True),
        rest=_still("◂"),
        ascii_rest=_still("<"),
        styles=("accent",),
    ),
    # A ripple spreading outward, like a ping dropped on the water. Same wake
    # glyph as the mark, used as an echo rather than a wake.
    "inspect": Motion(
        frames=("  ·  ", " ≈≈≈ ", "≈≈≈≈≈", " ≈≈≈ "),
        ascii_frames=("  .  ", " ~~~ ", "~~~~~", " ~~~ "),
        rest="  ·  ",
        ascii_rest="  .  ",
    ),
    # Cargo settling: the block elements of the wordmark's own letterforms,
    # sinking and rising. The most literal "made smaller" the set can manage.
    "compact": Motion(
        frames=(" ▄▄▄ ", " ▃▃▃ ", " ▂▂▂ ", " ▁▁▁ ", " ▂▂▂ ", " ▃▃▃ "),
        ascii_frames=(" ### ", " === ", " --- ", " ___ ", " --- ", " === "),
        rest=" ▃▃▃ ",
        ascii_rest=" === ",
    ),
    # A single solid mark. It was a three-cell shade ramp, which sat directly
    # under Compact's three-cell block bar and read as one object split over
    # two rows. Neighbours in a menu have to differ in *shape*, not only in
    # texture. Its animation is the colour rotating, so a lone chip is enough.
    "theme": Motion(
        frames=("  ◆  ",),
        ascii_frames=("  *  ",),
        rest="  ◆  ",
        ascii_rest="  *  ",
        styles=("primary", "accent", "success", "warning"),
    ),
    # The IEC power symbol, breathing dim to red the way a standby light does.
    "quit": Motion(
        frames=("  ⏻  ",),
        ascii_frames=(" (|) ",),
        rest="  ⏻  ",
        ascii_rest=" (|) ",
        styles=("dim", "error", "error", "dim"),
    ),
}
"""Per-action icons, keyed by the menu action name."""
