"""Animation state for Ferry's interface — pure data, no terminal involved.

Everything that moves on screen is defined here as a function of an integer
tick, so the renderers stay dumb and the behaviour stays testable. A frame is
just a string; picking one is ``frames[tick % len(frames)]``.

Two things animate:

- the **wake** under the ferry mark, a drifting pattern generated by
  :func:`wake_row` rather than hand-written frames, so it can be any width
- the **menu icons**, one :class:`Motion` per action, animated only while the
  row is under the cursor

Every glyph used here is on :data:`~ferry.cli.theme.TEXT_ONLY_GLYPHS` and was
checked against the Unicode ``emoji-data.txt`` Emoji property — see
``tests/test_motion.py``, which re-checks the whole set offline.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

__all__ = [
    "FRAME_SECONDS",
    "MENU_MOTION",
    "Motion",
    "WAKE_PERIOD",
    "moored_frame",
    "spinner_frames",
    "wake_row",
]

FRAME_SECONDS: Final = 0.12
"""Seconds per animation tick — about 8fps.

Deliberately slow. A repaint loop inside a full-screen prompt_toolkit
application costs a full redraw each tick, and over SSH or a slow terminal a
fast one strobes. Eight frames a second reads as motion without flickering.
"""

WAKE_PERIOD: Final = 3
"""Columns between one wake mark and the next."""


def wake_row(width: int, phase: int, *, mark: str = "≈", gap: str = " ") -> str:
    """One row of drifting wake.

    The marks sit every :data:`WAKE_PERIOD` columns and shift one column left
    per phase, so the water appears to flow past a stationary hull — which is
    what makes the ferry read as sailing to the right, the same direction the
    wordmark reveals.

    Args:
        width: How many columns to fill.
        phase: The animation tick. Any integer, including negative.
        mark: Glyph for a wake crest.
        gap: Glyph for the space between crests.

    Returns:
        A string exactly ``width`` characters long.
    """
    if width <= 0:
        return ""
    return "".join(mark if (col + phase) % WAKE_PERIOD == 0 else gap for col in range(width))


def spinner_frames(width: int = 6, *, ascii_only: bool = False) -> tuple[str, ...]:
    """The ferry spinner: a hull with wake trailing behind it.

    Used for indeterminate waits instead of a generic dot spinner, so the same
    mark that opens the program is the one that shows it working.

    Args:
        width: Columns of wake behind the hull.
        ascii_only: Use ASCII glyphs, for consoles that cannot encode the others.

    Returns:
        One frame per phase of the wake cycle.
    """
    mark, gap, hull = ("~", " ", ">") if ascii_only else ("≈", " ", "▸")
    return tuple(wake_row(width, phase, mark=mark, gap=gap) + hull for phase in range(WAKE_PERIOD))


def moored_frame(width: int = 3, *, ascii_only: bool = False) -> str:
    """The hull at rest with the wake settled, for when work has finished.

    Lives here rather than beside its caller so every glyph Ferry can draw
    stays inside the handful of modules the non-ASCII guard exempts.

    Args:
        width: Columns of (now empty) water behind the hull. Match whatever
            was passed to :func:`spinner_frames` so nothing shifts on arrival.
        ascii_only: Use ASCII glyphs.
    """
    return " " * width + (">" if ascii_only else "▸")


@dataclass(frozen=True)
class Motion:
    """An animated icon for one menu action.

    Args:
        frames: The animation, played while the row is selected.
        ascii_frames: The same animation in ASCII.
        rest: The still frame shown when the row is *not* selected. Separate
            from ``frames[0]`` on purpose — a resting icon should look calm,
            not like an animation paused at an arbitrary point.
        ascii_rest: ``rest`` in ASCII.
        styles: Theme colour tokens cycled alongside the frames. Usually one.
            The theme picker's own icon uses several, so its colour rotates
            while its glyph stays put.
    """

    frames: tuple[str, ...]
    ascii_frames: tuple[str, ...]
    rest: str
    ascii_rest: str
    styles: tuple[str, ...] = ("primary",)

    def __post_init__(self) -> None:
        if not self.frames or not self.ascii_frames or not self.styles:
            raise ValueError("a motion needs at least one frame and one style")
        if len({len(f) for f in self.frames} | {len(self.rest)}) != 1:
            raise ValueError(f"ragged frames would shift the label: {self.frames}")
        if len({len(f) for f in self.ascii_frames} | {len(self.ascii_rest)}) != 1:
            raise ValueError(f"ragged ascii frames: {self.ascii_frames}")
        if not "".join(self.ascii_frames + (self.ascii_rest,)).isascii():
            raise ValueError("ascii frames must actually be ascii")

    def frame(self, tick: int, *, selected: bool = True, ascii_only: bool = False) -> str:
        """The glyph to draw this tick."""
        if not selected:
            return self.ascii_rest if ascii_only else self.rest
        frames = self.ascii_frames if ascii_only else self.frames
        return frames[tick % len(frames)]

    def style(self, tick: int, *, selected: bool = True) -> str:
        """The theme colour token to draw it in."""
        if not selected:
            return "dim"
        return self.styles[tick % len(self.styles)]

    def width(self, *, ascii_only: bool = False) -> int:
        """Column width of this icon, constant across its frames."""
        return len(self.ascii_rest if ascii_only else self.rest)


MENU_MOTION: Final[dict[str, Motion]] = {
    # Export and import are deliberate mirror images: a hull leaving with its
    # wake behind it, and a hull arriving with its wake behind it the other
    # way. The two core operations should be distinguishable before the labels
    # are read.
    "export": Motion(
        frames=("≈▸", "·▸", " ▸", "·▸"),
        ascii_frames=("~>", "->", " >", "->"),
        rest=" ▸",
        ascii_rest=" >",
    ),
    "import": Motion(
        frames=("◂≈", "◂·", "◂ ", "◂·"),
        ascii_frames=("<~", "<-", "< ", "<-"),
        rest="◂ ",
        ascii_rest="< ",
        styles=("accent",),
    ),
    # An aperture opening and closing.
    "inspect": Motion(
        frames=("○ ", "◌ ", "◉ ", "◌ "),
        ascii_frames=("o ", ". ", "O ", ". "),
        rest="○ ",
        ascii_rest="o ",
    ),
    # Blocks settling downward — the shape of something being compressed.
    "compact": Motion(
        frames=("▄▄", "▃▃", "▂▂", "▁▁", "▂▂", "▃▃"),
        ascii_frames=("##", "==", "--", "__", "--", "=="),
        rest="▃▃",
        ascii_rest="==",
    ),
    # The glyph holds still and the colour rotates through the palette, which
    # is the one icon whose animation *is* its meaning.
    "theme": Motion(
        frames=("◆ ",),
        ascii_frames=("<>",),
        rest="◆ ",
        ascii_rest="<>",
        styles=("primary", "accent", "success", "warning"),
    ),
    # Moored. The only action that does not move.
    "quit": Motion(
        frames=("╵ ",),
        ascii_frames=("| ",),
        rest="╵ ",
        ascii_rest="| ",
        styles=("dim",),
    ),
}
"""Per-action icons, keyed by the menu action name."""
